# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-06-10 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0004_auto_20200610_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cve',
            old_name='notes',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='cveproduct',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='cveproducttype',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='cwe',
            old_name='name',
            new_name='cwe_id',
        ),
        migrations.AddField(
            model_name='cveproduct',
            name='cwe_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coding.CVEProductType'),
        ),
    ]
