# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-06-22 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0008_auto_20200610_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='cve',
            name='consequences',
            field=models.TextField(default=b'', null=True),
        ),
        migrations.AddField(
            model_name='cve',
            name='how',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='coding.CodingTagHow'),
        ),
        migrations.AddField(
            model_name='cve',
            name='mitigation',
            field=models.TextField(default=b'', null=True),
        ),
        migrations.AddField(
            model_name='cve',
            name='what',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='coding.CodingTagWhat'),
        ),
        migrations.AddField(
            model_name='cve',
            name='where',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='coding.CodingTagWhere'),
        ),
        migrations.AlterField(
            model_name='cve',
            name='notes',
            field=models.TextField(default=b'', null=True),
        ),
        migrations.AlterField(
            model_name='cwe',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
