# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-06-10 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0002_auto_20200604_1405'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CVEProductName',
            new_name='CVEProduct',
        ),
    ]
