# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-06-10 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0006_auto_20200610_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cve',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
