# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-06-10 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0007_auto_20200610_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cveproduct',
            old_name='cwe_tag',
            new_name='product_type',
        ),
        migrations.AddField(
            model_name='cve',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coding.CVEProduct'),
        ),
    ]
